'use strict';

const fs   = require('fs');
const path = require('path');

const WASM_FILE   = '../lib/mathlib/wasm/math.wasm';
const WASM_BASE64 = '../lib/mathlib/wasm/math_wasm_base64.js';

const wasm = fs.readFileSync(path.join(__dirname, WASM_FILE));

const encoded = `// This is autogenerated file from math.wasm, don't edit.
//
'use strict';

/* eslint-disable max-len */
module.exports = '${wasm.toString('base64')}';
`;

fs.writeFileSync(path.join(__dirname, WASM_BASE64), encoded);
