name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24 ]

    steps:
    - uses: actions/checkout@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Run tests
      run: npm test
